
### Variables
@token=6f16982b35ac2168f86c7978b7b42967528939b066598326139e0963510a
@username=bruckins
@blueprint=sql
@workspacename=dev-bruckins

### Get All Workspaces
GET http://localhost:9201/api/v1/workspaces
Authorization: Bearer {{token}}

### Delete Workspace
DELETE http://localhost:9201/api/v1/workspaces/vitvatom-3aaeba5
Authorization: Bearer {{token}}

### Get Single Workspace

GET http://localhost:9201/api/v1/workspaces?username={{username}}&blueprint={{blueprint}}
Authorization: Bearer {{token}}

### Get Workspace Status
GET http://localhost:9201/api/v1/workspaces/dev-bruckins/status
Authorization: Bearer {{token}}

### Provision Workspace
POST http://localhost:9201/api/v1/workspaces?stream=true&username={{username}}&blueprint={{blueprint}}
Authorization: Bearer {{token}}
