{{ if .Values.__registry__.dockerConfigJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.__registry__.regcred }}
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.__registry__.dockerConfigJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{ end }}
