// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/api/provisioner.proto

package provisionerpb

import (
	commonpb "github.com/k8shell-io/common/pkg/gapi/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{0}
}

func (x *Workspace) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type GetUserWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Blueprint     string                 `protobuf:"bytes,2,opt,name=blueprint,proto3" json:"blueprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserWorkspacesRequest) Reset() {
	*x = GetUserWorkspacesRequest{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserWorkspacesRequest) ProtoMessage() {}

func (x *GetUserWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*GetUserWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserWorkspacesRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserWorkspacesRequest) GetBlueprint() string {
	if x != nil {
		return x.Blueprint
	}
	return ""
}

type ListWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Blueprint     string                 `protobuf:"bytes,2,opt,name=blueprint,proto3" json:"blueprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesRequest) Reset() {
	*x = ListWorkspacesRequest{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesRequest) ProtoMessage() {}

func (x *ListWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*ListWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{2}
}

func (x *ListWorkspacesRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ListWorkspacesRequest) GetBlueprint() string {
	if x != nil {
		return x.Blueprint
	}
	return ""
}

type ListWorkspacesResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Workspaces    []*commonpb.WorkspaceInfo `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesResponse) Reset() {
	*x = ListWorkspacesResponse{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesResponse) ProtoMessage() {}

func (x *ListWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{3}
}

func (x *ListWorkspacesResponse) GetWorkspaces() []*commonpb.WorkspaceInfo {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type ProvisionWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userstr       string                 `protobuf:"bytes,1,opt,name=userstr,proto3" json:"userstr,omitempty"`
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionWorkspaceRequest) Reset() {
	*x = ProvisionWorkspaceRequest{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionWorkspaceRequest) ProtoMessage() {}

func (x *ProvisionWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*ProvisionWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{4}
}

func (x *ProvisionWorkspaceRequest) GetUserstr() string {
	if x != nil {
		return x.Userstr
	}
	return ""
}

func (x *ProvisionWorkspaceRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type ProvisionWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionWorkspaceResponse) Reset() {
	*x = ProvisionWorkspaceResponse{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionWorkspaceResponse) ProtoMessage() {}

func (x *ProvisionWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*ProvisionWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{5}
}

func (x *ProvisionWorkspaceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProvisionWorkspaceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProvisionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ObjectName    string                 `protobuf:"bytes,3,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionEvent) Reset() {
	*x = ProvisionEvent{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionEvent) ProtoMessage() {}

func (x *ProvisionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionEvent.ProtoReflect.Descriptor instead.
func (*ProvisionEvent) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{6}
}

func (x *ProvisionEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProvisionEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ProvisionEvent) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *ProvisionEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProvisionEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceResponse) Reset() {
	*x = DeleteWorkspaceResponse{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceResponse) ProtoMessage() {}

func (x *DeleteWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteWorkspaceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RestartWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartWorkspaceResponse) Reset() {
	*x = RestartWorkspaceResponse{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartWorkspaceResponse) ProtoMessage() {}

func (x *RestartWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*RestartWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{8}
}

func (x *RestartWorkspaceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_api_provisioner_proto protoreflect.FileDescriptor

const file_pkg_api_provisioner_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/api/provisioner.proto\x12\vprovisioner\x1a\x1ccommon/pkg/gapi/common.proto\")\n" +
	"\tWorkspace\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\"T\n" +
	"\x18GetUserWorkspacesRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1c\n" +
	"\tblueprint\x18\x02 \x01(\tR\tblueprint\"Q\n" +
	"\x15ListWorkspacesRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1c\n" +
	"\tblueprint\x18\x02 \x01(\tR\tblueprint\"O\n" +
	"\x16ListWorkspacesResponse\x125\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x15.common.WorkspaceInfoR\n" +
	"workspaces\"O\n" +
	"\x19ProvisionWorkspaceRequest\x12\x18\n" +
	"\auserstr\x18\x01 \x01(\tR\auserstr\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\"N\n" +
	"\x1aProvisionWorkspaceResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x95\x01\n" +
	"\x0eProvisionEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x1f\n" +
	"\vobject_name\x18\x03 \x01(\tR\n" +
	"objectName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"3\n" +
	"\x17DeleteWorkspaceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"4\n" +
	"\x18RestartWorkspaceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x93\x04\n" +
	"\x12ProvisionerService\x12T\n" +
	"\x14GetUserWorkspaceInfo\x12%.provisioner.GetUserWorkspacesRequest\x1a\x15.common.WorkspaceInfo\x12E\n" +
	"\x12GetWorkspaceStatus\x12\x16.provisioner.Workspace\x1a\x17.common.WorkspaceStatus\x12Y\n" +
	"\x0eListWorkspaces\x12\".provisioner.ListWorkspacesRequest\x1a#.provisioner.ListWorkspacesResponse\x12a\n" +
	"\x18ProvisionWorkspaceStream\x12&.provisioner.ProvisionWorkspaceRequest\x1a\x1b.provisioner.ProvisionEvent0\x01\x12O\n" +
	"\x0fDeleteWorkspace\x12\x16.provisioner.Workspace\x1a$.provisioner.DeleteWorkspaceResponse\x12Q\n" +
	"\x10RestartWorkspace\x12\x16.provisioner.Workspace\x1a%.provisioner.RestartWorkspaceResponseBGZEgithub.com/k8shell-io/provisioner/pkg/api/provisionerpb;provisionerpbb\x06proto3"

var (
	file_pkg_api_provisioner_proto_rawDescOnce sync.Once
	file_pkg_api_provisioner_proto_rawDescData []byte
)

func file_pkg_api_provisioner_proto_rawDescGZIP() []byte {
	file_pkg_api_provisioner_proto_rawDescOnce.Do(func() {
		file_pkg_api_provisioner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_provisioner_proto_rawDesc), len(file_pkg_api_provisioner_proto_rawDesc)))
	})
	return file_pkg_api_provisioner_proto_rawDescData
}

var file_pkg_api_provisioner_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_api_provisioner_proto_goTypes = []any{
	(*Workspace)(nil),                  // 0: provisioner.Workspace
	(*GetUserWorkspacesRequest)(nil),   // 1: provisioner.GetUserWorkspacesRequest
	(*ListWorkspacesRequest)(nil),      // 2: provisioner.ListWorkspacesRequest
	(*ListWorkspacesResponse)(nil),     // 3: provisioner.ListWorkspacesResponse
	(*ProvisionWorkspaceRequest)(nil),  // 4: provisioner.ProvisionWorkspaceRequest
	(*ProvisionWorkspaceResponse)(nil), // 5: provisioner.ProvisionWorkspaceResponse
	(*ProvisionEvent)(nil),             // 6: provisioner.ProvisionEvent
	(*DeleteWorkspaceResponse)(nil),    // 7: provisioner.DeleteWorkspaceResponse
	(*RestartWorkspaceResponse)(nil),   // 8: provisioner.RestartWorkspaceResponse
	(*commonpb.WorkspaceInfo)(nil),     // 9: common.WorkspaceInfo
	(*commonpb.WorkspaceStatus)(nil),   // 10: common.WorkspaceStatus
}
var file_pkg_api_provisioner_proto_depIdxs = []int32{
	9,  // 0: provisioner.ListWorkspacesResponse.workspaces:type_name -> common.WorkspaceInfo
	1,  // 1: provisioner.ProvisionerService.GetUserWorkspaceInfo:input_type -> provisioner.GetUserWorkspacesRequest
	0,  // 2: provisioner.ProvisionerService.GetWorkspaceStatus:input_type -> provisioner.Workspace
	2,  // 3: provisioner.ProvisionerService.ListWorkspaces:input_type -> provisioner.ListWorkspacesRequest
	4,  // 4: provisioner.ProvisionerService.ProvisionWorkspaceStream:input_type -> provisioner.ProvisionWorkspaceRequest
	0,  // 5: provisioner.ProvisionerService.DeleteWorkspace:input_type -> provisioner.Workspace
	0,  // 6: provisioner.ProvisionerService.RestartWorkspace:input_type -> provisioner.Workspace
	9,  // 7: provisioner.ProvisionerService.GetUserWorkspaceInfo:output_type -> common.WorkspaceInfo
	10, // 8: provisioner.ProvisionerService.GetWorkspaceStatus:output_type -> common.WorkspaceStatus
	3,  // 9: provisioner.ProvisionerService.ListWorkspaces:output_type -> provisioner.ListWorkspacesResponse
	6,  // 10: provisioner.ProvisionerService.ProvisionWorkspaceStream:output_type -> provisioner.ProvisionEvent
	7,  // 11: provisioner.ProvisionerService.DeleteWorkspace:output_type -> provisioner.DeleteWorkspaceResponse
	8,  // 12: provisioner.ProvisionerService.RestartWorkspace:output_type -> provisioner.RestartWorkspaceResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_api_provisioner_proto_init() }
func file_pkg_api_provisioner_proto_init() {
	if File_pkg_api_provisioner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_provisioner_proto_rawDesc), len(file_pkg_api_provisioner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_provisioner_proto_goTypes,
		DependencyIndexes: file_pkg_api_provisioner_proto_depIdxs,
		MessageInfos:      file_pkg_api_provisioner_proto_msgTypes,
	}.Build()
	File_pkg_api_provisioner_proto = out.File
	file_pkg_api_provisioner_proto_goTypes = nil
	file_pkg_api_provisioner_proto_depIdxs = nil
}
