// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/api/provisioner.proto

package provisionerpb

import (
	commonpb "github.com/k8shell-io/common/pkg/gapi/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindWorkspaceRequest) Reset() {
	*x = FindWorkspaceRequest{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindWorkspaceRequest) ProtoMessage() {}

func (x *FindWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*FindWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{0}
}

func (x *FindWorkspaceRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type GetWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Organization  string                 `protobuf:"bytes,3,opt,name=organization,proto3" json:"organization,omitempty"`
	Blueprint     string                 `protobuf:"bytes,4,opt,name=blueprint,proto3" json:"blueprint,omitempty"`
	RepoName      string                 `protobuf:"bytes,5,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	RepoOwner     string                 `protobuf:"bytes,6,opt,name=repo_owner,json=repoOwner,proto3" json:"repo_owner,omitempty"`
	RepoRef       string                 `protobuf:"bytes,7,opt,name=repo_ref,json=repoRef,proto3" json:"repo_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspacesRequest) Reset() {
	*x = GetWorkspacesRequest{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspacesRequest) ProtoMessage() {}

func (x *GetWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{1}
}

func (x *GetWorkspacesRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *GetWorkspacesRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetWorkspacesRequest) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *GetWorkspacesRequest) GetBlueprint() string {
	if x != nil {
		return x.Blueprint
	}
	return ""
}

func (x *GetWorkspacesRequest) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *GetWorkspacesRequest) GetRepoOwner() string {
	if x != nil {
		return x.RepoOwner
	}
	return ""
}

func (x *GetWorkspacesRequest) GetRepoRef() string {
	if x != nil {
		return x.RepoRef
	}
	return ""
}

type GetWorkspacesResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Workspaces    []*commonpb.WorkspaceDetails `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspacesResponse) Reset() {
	*x = GetWorkspacesResponse{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspacesResponse) ProtoMessage() {}

func (x *GetWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*GetWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorkspacesResponse) GetWorkspaces() []*commonpb.WorkspaceDetails {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type GetUserBlueprintsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBlueprintsRequest) Reset() {
	*x = GetUserBlueprintsRequest{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBlueprintsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBlueprintsRequest) ProtoMessage() {}

func (x *GetUserBlueprintsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBlueprintsRequest.ProtoReflect.Descriptor instead.
func (*GetUserBlueprintsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserBlueprintsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type BlueprintSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlueprintSummary) Reset() {
	*x = BlueprintSummary{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlueprintSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlueprintSummary) ProtoMessage() {}

func (x *BlueprintSummary) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlueprintSummary.ProtoReflect.Descriptor instead.
func (*BlueprintSummary) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{4}
}

func (x *BlueprintSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BlueprintSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetUserBlueprintsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blueprints    []*BlueprintSummary    `protobuf:"bytes,1,rep,name=blueprints,proto3" json:"blueprints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBlueprintsResponse) Reset() {
	*x = GetUserBlueprintsResponse{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBlueprintsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBlueprintsResponse) ProtoMessage() {}

func (x *GetUserBlueprintsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBlueprintsResponse.ProtoReflect.Descriptor instead.
func (*GetUserBlueprintsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserBlueprintsResponse) GetBlueprints() []*BlueprintSummary {
	if x != nil {
		return x.Blueprints
	}
	return nil
}

type ProvisionWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userstr       string                 `protobuf:"bytes,1,opt,name=userstr,proto3" json:"userstr,omitempty"`
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	SendProgress  bool                   `protobuf:"varint,3,opt,name=sendProgress,proto3" json:"sendProgress,omitempty"`
	SendEvents    bool                   `protobuf:"varint,4,opt,name=sendEvents,proto3" json:"sendEvents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionWorkspaceRequest) Reset() {
	*x = ProvisionWorkspaceRequest{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionWorkspaceRequest) ProtoMessage() {}

func (x *ProvisionWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*ProvisionWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{6}
}

func (x *ProvisionWorkspaceRequest) GetUserstr() string {
	if x != nil {
		return x.Userstr
	}
	return ""
}

func (x *ProvisionWorkspaceRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ProvisionWorkspaceRequest) GetSendProgress() bool {
	if x != nil {
		return x.SendProgress
	}
	return false
}

func (x *ProvisionWorkspaceRequest) GetSendEvents() bool {
	if x != nil {
		return x.SendEvents
	}
	return false
}

type ProvisionWorkspaceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*ProvisionWorkspaceResponse_Handshake
	//	*ProvisionWorkspaceResponse_Event
	Data          isProvisionWorkspaceResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionWorkspaceResponse) Reset() {
	*x = ProvisionWorkspaceResponse{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionWorkspaceResponse) ProtoMessage() {}

func (x *ProvisionWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*ProvisionWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{7}
}

func (x *ProvisionWorkspaceResponse) GetData() isProvisionWorkspaceResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProvisionWorkspaceResponse) GetHandshake() *HandshakeResponse {
	if x != nil {
		if x, ok := x.Data.(*ProvisionWorkspaceResponse_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *ProvisionWorkspaceResponse) GetEvent() *ProvisionEvent {
	if x != nil {
		if x, ok := x.Data.(*ProvisionWorkspaceResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isProvisionWorkspaceResponse_Data interface {
	isProvisionWorkspaceResponse_Data()
}

type ProvisionWorkspaceResponse_Handshake struct {
	Handshake *HandshakeResponse `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type ProvisionWorkspaceResponse_Event struct {
	Event *ProvisionEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

func (*ProvisionWorkspaceResponse_Handshake) isProvisionWorkspaceResponse_Data() {}

func (*ProvisionWorkspaceResponse_Event) isProvisionWorkspaceResponse_Data() {}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Jobid         string                 `protobuf:"bytes,2,opt,name=jobid,proto3" json:"jobid,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{8}
}

func (x *HandshakeResponse) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *HandshakeResponse) GetJobid() string {
	if x != nil {
		return x.Jobid
	}
	return ""
}

func (x *HandshakeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpgradeWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	SendProgress  bool                   `protobuf:"varint,3,opt,name=sendProgress,proto3" json:"sendProgress,omitempty"`
	SendEvents    bool                   `protobuf:"varint,4,opt,name=sendEvents,proto3" json:"sendEvents,omitempty"`
	Force         bool                   `protobuf:"varint,5,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeWorkspaceRequest) Reset() {
	*x = UpgradeWorkspaceRequest{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeWorkspaceRequest) ProtoMessage() {}

func (x *UpgradeWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*UpgradeWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{9}
}

func (x *UpgradeWorkspaceRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *UpgradeWorkspaceRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *UpgradeWorkspaceRequest) GetSendProgress() bool {
	if x != nil {
		return x.SendProgress
	}
	return false
}

func (x *UpgradeWorkspaceRequest) GetSendEvents() bool {
	if x != nil {
		return x.SendEvents
	}
	return false
}

func (x *UpgradeWorkspaceRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type UpgradeWorkspaceResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Cpu           string                 `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeWorkspaceResourcesRequest) Reset() {
	*x = UpgradeWorkspaceResourcesRequest{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeWorkspaceResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeWorkspaceResourcesRequest) ProtoMessage() {}

func (x *UpgradeWorkspaceResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeWorkspaceResourcesRequest.ProtoReflect.Descriptor instead.
func (*UpgradeWorkspaceResourcesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{10}
}

func (x *UpgradeWorkspaceResourcesRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *UpgradeWorkspaceResourcesRequest) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *UpgradeWorkspaceResourcesRequest) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

type UpgradeWorkspaceResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeWorkspaceResourcesResponse) Reset() {
	*x = UpgradeWorkspaceResourcesResponse{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeWorkspaceResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeWorkspaceResourcesResponse) ProtoMessage() {}

func (x *UpgradeWorkspaceResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeWorkspaceResourcesResponse.ProtoReflect.Descriptor instead.
func (*UpgradeWorkspaceResourcesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{11}
}

func (x *UpgradeWorkspaceResourcesResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpgradeWorkspaceResourcesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProvisionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ObjectName    string                 `protobuf:"bytes,3,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionEvent) Reset() {
	*x = ProvisionEvent{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionEvent) ProtoMessage() {}

func (x *ProvisionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionEvent.ProtoReflect.Descriptor instead.
func (*ProvisionEvent) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{12}
}

func (x *ProvisionEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProvisionEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ProvisionEvent) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *ProvisionEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProvisionEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	DelaySeconds  uint32                 `protobuf:"varint,2,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceRequest) Reset() {
	*x = DeleteWorkspaceRequest{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceRequest) ProtoMessage() {}

func (x *DeleteWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteWorkspaceRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *DeleteWorkspaceRequest) GetDelaySeconds() uint32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

type DeleteWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceResponse) Reset() {
	*x = DeleteWorkspaceResponse{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceResponse) ProtoMessage() {}

func (x *DeleteWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteWorkspaceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CanUpgradeWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanUpgradeWorkspaceRequest) Reset() {
	*x = CanUpgradeWorkspaceRequest{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanUpgradeWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanUpgradeWorkspaceRequest) ProtoMessage() {}

func (x *CanUpgradeWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanUpgradeWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CanUpgradeWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{15}
}

func (x *CanUpgradeWorkspaceRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type CanUpgradeWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanUpgrade    bool                   `protobuf:"varint,1,opt,name=can_upgrade,json=canUpgrade,proto3" json:"can_upgrade,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanUpgradeWorkspaceResponse) Reset() {
	*x = CanUpgradeWorkspaceResponse{}
	mi := &file_pkg_api_provisioner_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanUpgradeWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanUpgradeWorkspaceResponse) ProtoMessage() {}

func (x *CanUpgradeWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_provisioner_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanUpgradeWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*CanUpgradeWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_provisioner_proto_rawDescGZIP(), []int{16}
}

func (x *CanUpgradeWorkspaceResponse) GetCanUpgrade() bool {
	if x != nil {
		return x.CanUpgrade
	}
	return false
}

func (x *CanUpgradeWorkspaceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_api_provisioner_proto protoreflect.FileDescriptor

const file_pkg_api_provisioner_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/api/provisioner.proto\x12\vprovisioner\x1a\x1ccommon/pkg/gapi/common.proto\"4\n" +
	"\x14FindWorkspaceRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\"\xe9\x01\n" +
	"\x14GetWorkspacesRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\"\n" +
	"\forganization\x18\x03 \x01(\tR\forganization\x12\x1c\n" +
	"\tblueprint\x18\x04 \x01(\tR\tblueprint\x12\x1b\n" +
	"\trepo_name\x18\x05 \x01(\tR\brepoName\x12\x1d\n" +
	"\n" +
	"repo_owner\x18\x06 \x01(\tR\trepoOwner\x12\x19\n" +
	"\brepo_ref\x18\a \x01(\tR\arepoRef\"Q\n" +
	"\x15GetWorkspacesResponse\x128\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x18.common.WorkspaceDetailsR\n" +
	"workspaces\"6\n" +
	"\x18GetUserBlueprintsRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"H\n" +
	"\x10BlueprintSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"Z\n" +
	"\x19GetUserBlueprintsResponse\x12=\n" +
	"\n" +
	"blueprints\x18\x01 \x03(\v2\x1d.provisioner.BlueprintSummaryR\n" +
	"blueprints\"\x93\x01\n" +
	"\x19ProvisionWorkspaceRequest\x12\x18\n" +
	"\auserstr\x18\x01 \x01(\tR\auserstr\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\x12\"\n" +
	"\fsendProgress\x18\x03 \x01(\bR\fsendProgress\x12\x1e\n" +
	"\n" +
	"sendEvents\x18\x04 \x01(\bR\n" +
	"sendEvents\"\x99\x01\n" +
	"\x1aProvisionWorkspaceResponse\x12>\n" +
	"\thandshake\x18\x01 \x01(\v2\x1e.provisioner.HandshakeResponseH\x00R\thandshake\x123\n" +
	"\x05event\x18\x02 \x01(\v2\x1b.provisioner.ProvisionEventH\x00R\x05eventB\x06\n" +
	"\x04data\"]\n" +
	"\x11HandshakeResponse\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x14\n" +
	"\x05jobid\x18\x02 \x01(\tR\x05jobid\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xab\x01\n" +
	"\x17UpgradeWorkspaceRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\x12\"\n" +
	"\fsendProgress\x18\x03 \x01(\bR\fsendProgress\x12\x1e\n" +
	"\n" +
	"sendEvents\x18\x04 \x01(\bR\n" +
	"sendEvents\x12\x14\n" +
	"\x05force\x18\x05 \x01(\bR\x05force\"j\n" +
	" UpgradeWorkspaceResourcesRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\tR\x06memory\"U\n" +
	"!UpgradeWorkspaceResourcesResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x95\x01\n" +
	"\x0eProvisionEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x1f\n" +
	"\vobject_name\x18\x03 \x01(\tR\n" +
	"objectName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"[\n" +
	"\x16DeleteWorkspaceRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12#\n" +
	"\rdelay_seconds\x18\x02 \x01(\rR\fdelaySeconds\"3\n" +
	"\x17DeleteWorkspaceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\":\n" +
	"\x1aCanUpgradeWorkspaceRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\"X\n" +
	"\x1bCanUpgradeWorkspaceResponse\x12\x1f\n" +
	"\vcan_upgrade\x18\x01 \x01(\bR\n" +
	"canUpgrade\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb6\x06\n" +
	"\x12ProvisionerService\x12V\n" +
	"\rGetWorkspaces\x12!.provisioner.GetWorkspacesRequest\x1a\".provisioner.GetWorkspacesResponse\x12L\n" +
	"\rFindWorkspace\x12!.provisioner.FindWorkspaceRequest\x1a\x18.common.WorkspaceDetails\x12b\n" +
	"\x11GetUserBlueprints\x12%.provisioner.GetUserBlueprintsRequest\x1a&.provisioner.GetUserBlueprintsResponse\x12m\n" +
	"\x18ProvisionWorkspaceStream\x12&.provisioner.ProvisionWorkspaceRequest\x1a'.provisioner.ProvisionWorkspaceResponse0\x01\x12h\n" +
	"\x13CanUpgradeWorkspace\x12'.provisioner.CanUpgradeWorkspaceRequest\x1a(.provisioner.CanUpgradeWorkspaceResponse\x12z\n" +
	"\x19UpgradeWorkspaceResources\x12-.provisioner.UpgradeWorkspaceResourcesRequest\x1a..provisioner.UpgradeWorkspaceResourcesResponse\x12c\n" +
	"\x10UpgradeWorkspace\x12$.provisioner.UpgradeWorkspaceRequest\x1a'.provisioner.ProvisionWorkspaceResponse0\x01\x12\\\n" +
	"\x0fDeleteWorkspace\x12#.provisioner.DeleteWorkspaceRequest\x1a$.provisioner.DeleteWorkspaceResponseBGZEgithub.com/k8shell-io/provisioner/pkg/api/provisionerpb;provisionerpbb\x06proto3"

var (
	file_pkg_api_provisioner_proto_rawDescOnce sync.Once
	file_pkg_api_provisioner_proto_rawDescData []byte
)

func file_pkg_api_provisioner_proto_rawDescGZIP() []byte {
	file_pkg_api_provisioner_proto_rawDescOnce.Do(func() {
		file_pkg_api_provisioner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_provisioner_proto_rawDesc), len(file_pkg_api_provisioner_proto_rawDesc)))
	})
	return file_pkg_api_provisioner_proto_rawDescData
}

var file_pkg_api_provisioner_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pkg_api_provisioner_proto_goTypes = []any{
	(*FindWorkspaceRequest)(nil),              // 0: provisioner.FindWorkspaceRequest
	(*GetWorkspacesRequest)(nil),              // 1: provisioner.GetWorkspacesRequest
	(*GetWorkspacesResponse)(nil),             // 2: provisioner.GetWorkspacesResponse
	(*GetUserBlueprintsRequest)(nil),          // 3: provisioner.GetUserBlueprintsRequest
	(*BlueprintSummary)(nil),                  // 4: provisioner.BlueprintSummary
	(*GetUserBlueprintsResponse)(nil),         // 5: provisioner.GetUserBlueprintsResponse
	(*ProvisionWorkspaceRequest)(nil),         // 6: provisioner.ProvisionWorkspaceRequest
	(*ProvisionWorkspaceResponse)(nil),        // 7: provisioner.ProvisionWorkspaceResponse
	(*HandshakeResponse)(nil),                 // 8: provisioner.HandshakeResponse
	(*UpgradeWorkspaceRequest)(nil),           // 9: provisioner.UpgradeWorkspaceRequest
	(*UpgradeWorkspaceResourcesRequest)(nil),  // 10: provisioner.UpgradeWorkspaceResourcesRequest
	(*UpgradeWorkspaceResourcesResponse)(nil), // 11: provisioner.UpgradeWorkspaceResourcesResponse
	(*ProvisionEvent)(nil),                    // 12: provisioner.ProvisionEvent
	(*DeleteWorkspaceRequest)(nil),            // 13: provisioner.DeleteWorkspaceRequest
	(*DeleteWorkspaceResponse)(nil),           // 14: provisioner.DeleteWorkspaceResponse
	(*CanUpgradeWorkspaceRequest)(nil),        // 15: provisioner.CanUpgradeWorkspaceRequest
	(*CanUpgradeWorkspaceResponse)(nil),       // 16: provisioner.CanUpgradeWorkspaceResponse
	(*commonpb.WorkspaceDetails)(nil),         // 17: common.WorkspaceDetails
}
var file_pkg_api_provisioner_proto_depIdxs = []int32{
	17, // 0: provisioner.GetWorkspacesResponse.workspaces:type_name -> common.WorkspaceDetails
	4,  // 1: provisioner.GetUserBlueprintsResponse.blueprints:type_name -> provisioner.BlueprintSummary
	8,  // 2: provisioner.ProvisionWorkspaceResponse.handshake:type_name -> provisioner.HandshakeResponse
	12, // 3: provisioner.ProvisionWorkspaceResponse.event:type_name -> provisioner.ProvisionEvent
	1,  // 4: provisioner.ProvisionerService.GetWorkspaces:input_type -> provisioner.GetWorkspacesRequest
	0,  // 5: provisioner.ProvisionerService.FindWorkspace:input_type -> provisioner.FindWorkspaceRequest
	3,  // 6: provisioner.ProvisionerService.GetUserBlueprints:input_type -> provisioner.GetUserBlueprintsRequest
	6,  // 7: provisioner.ProvisionerService.ProvisionWorkspaceStream:input_type -> provisioner.ProvisionWorkspaceRequest
	15, // 8: provisioner.ProvisionerService.CanUpgradeWorkspace:input_type -> provisioner.CanUpgradeWorkspaceRequest
	10, // 9: provisioner.ProvisionerService.UpgradeWorkspaceResources:input_type -> provisioner.UpgradeWorkspaceResourcesRequest
	9,  // 10: provisioner.ProvisionerService.UpgradeWorkspace:input_type -> provisioner.UpgradeWorkspaceRequest
	13, // 11: provisioner.ProvisionerService.DeleteWorkspace:input_type -> provisioner.DeleteWorkspaceRequest
	2,  // 12: provisioner.ProvisionerService.GetWorkspaces:output_type -> provisioner.GetWorkspacesResponse
	17, // 13: provisioner.ProvisionerService.FindWorkspace:output_type -> common.WorkspaceDetails
	5,  // 14: provisioner.ProvisionerService.GetUserBlueprints:output_type -> provisioner.GetUserBlueprintsResponse
	7,  // 15: provisioner.ProvisionerService.ProvisionWorkspaceStream:output_type -> provisioner.ProvisionWorkspaceResponse
	16, // 16: provisioner.ProvisionerService.CanUpgradeWorkspace:output_type -> provisioner.CanUpgradeWorkspaceResponse
	11, // 17: provisioner.ProvisionerService.UpgradeWorkspaceResources:output_type -> provisioner.UpgradeWorkspaceResourcesResponse
	7,  // 18: provisioner.ProvisionerService.UpgradeWorkspace:output_type -> provisioner.ProvisionWorkspaceResponse
	14, // 19: provisioner.ProvisionerService.DeleteWorkspace:output_type -> provisioner.DeleteWorkspaceResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_api_provisioner_proto_init() }
func file_pkg_api_provisioner_proto_init() {
	if File_pkg_api_provisioner_proto != nil {
		return
	}
	file_pkg_api_provisioner_proto_msgTypes[7].OneofWrappers = []any{
		(*ProvisionWorkspaceResponse_Handshake)(nil),
		(*ProvisionWorkspaceResponse_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_provisioner_proto_rawDesc), len(file_pkg_api_provisioner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_provisioner_proto_goTypes,
		DependencyIndexes: file_pkg_api_provisioner_proto_depIdxs,
		MessageInfos:      file_pkg_api_provisioner_proto_msgTypes,
	}.Build()
	File_pkg_api_provisioner_proto = out.File
	file_pkg_api_provisioner_proto_goTypes = nil
	file_pkg_api_provisioner_proto_depIdxs = nil
}
