// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pkg/api/provisioner.proto

package provisionerpb

import (
	context "context"
	commonpb "github.com/k8shell-io/common/pkg/gapi/commonpb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProvisionerService_GetUserWorkspaceInfo_FullMethodName     = "/provisioner.ProvisionerService/GetUserWorkspaceInfo"
	ProvisionerService_GetWorkspaceStatus_FullMethodName       = "/provisioner.ProvisionerService/GetWorkspaceStatus"
	ProvisionerService_ListWorkspaces_FullMethodName           = "/provisioner.ProvisionerService/ListWorkspaces"
	ProvisionerService_ProvisionWorkspaceStream_FullMethodName = "/provisioner.ProvisionerService/ProvisionWorkspaceStream"
	ProvisionerService_DeleteWorkspace_FullMethodName          = "/provisioner.ProvisionerService/DeleteWorkspace"
)

// ProvisionerServiceClient is the client API for ProvisionerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProvisionerServiceClient interface {
	GetUserWorkspaceInfo(ctx context.Context, in *GetUserWorkspacesRequest, opts ...grpc.CallOption) (*commonpb.WorkspaceInfo, error)
	GetWorkspaceStatus(ctx context.Context, in *Workspace, opts ...grpc.CallOption) (*commonpb.WorkspaceStatus, error)
	ListWorkspaces(ctx context.Context, in *ListWorkspacesRequest, opts ...grpc.CallOption) (*ListWorkspacesResponse, error)
	ProvisionWorkspaceStream(ctx context.Context, in *ProvisionWorkspaceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProvisionEvent], error)
	DeleteWorkspace(ctx context.Context, in *Workspace, opts ...grpc.CallOption) (*DeleteWorkspaceResponse, error)
}

type provisionerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProvisionerServiceClient(cc grpc.ClientConnInterface) ProvisionerServiceClient {
	return &provisionerServiceClient{cc}
}

func (c *provisionerServiceClient) GetUserWorkspaceInfo(ctx context.Context, in *GetUserWorkspacesRequest, opts ...grpc.CallOption) (*commonpb.WorkspaceInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.WorkspaceInfo)
	err := c.cc.Invoke(ctx, ProvisionerService_GetUserWorkspaceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionerServiceClient) GetWorkspaceStatus(ctx context.Context, in *Workspace, opts ...grpc.CallOption) (*commonpb.WorkspaceStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(commonpb.WorkspaceStatus)
	err := c.cc.Invoke(ctx, ProvisionerService_GetWorkspaceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionerServiceClient) ListWorkspaces(ctx context.Context, in *ListWorkspacesRequest, opts ...grpc.CallOption) (*ListWorkspacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkspacesResponse)
	err := c.cc.Invoke(ctx, ProvisionerService_ListWorkspaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionerServiceClient) ProvisionWorkspaceStream(ctx context.Context, in *ProvisionWorkspaceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProvisionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProvisionerService_ServiceDesc.Streams[0], ProvisionerService_ProvisionWorkspaceStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProvisionWorkspaceRequest, ProvisionEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProvisionerService_ProvisionWorkspaceStreamClient = grpc.ServerStreamingClient[ProvisionEvent]

func (c *provisionerServiceClient) DeleteWorkspace(ctx context.Context, in *Workspace, opts ...grpc.CallOption) (*DeleteWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWorkspaceResponse)
	err := c.cc.Invoke(ctx, ProvisionerService_DeleteWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProvisionerServiceServer is the server API for ProvisionerService service.
// All implementations must embed UnimplementedProvisionerServiceServer
// for forward compatibility.
type ProvisionerServiceServer interface {
	GetUserWorkspaceInfo(context.Context, *GetUserWorkspacesRequest) (*commonpb.WorkspaceInfo, error)
	GetWorkspaceStatus(context.Context, *Workspace) (*commonpb.WorkspaceStatus, error)
	ListWorkspaces(context.Context, *ListWorkspacesRequest) (*ListWorkspacesResponse, error)
	ProvisionWorkspaceStream(*ProvisionWorkspaceRequest, grpc.ServerStreamingServer[ProvisionEvent]) error
	DeleteWorkspace(context.Context, *Workspace) (*DeleteWorkspaceResponse, error)
	mustEmbedUnimplementedProvisionerServiceServer()
}

// UnimplementedProvisionerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProvisionerServiceServer struct{}

func (UnimplementedProvisionerServiceServer) GetUserWorkspaceInfo(context.Context, *GetUserWorkspacesRequest) (*commonpb.WorkspaceInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserWorkspaceInfo not implemented")
}
func (UnimplementedProvisionerServiceServer) GetWorkspaceStatus(context.Context, *Workspace) (*commonpb.WorkspaceStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkspaceStatus not implemented")
}
func (UnimplementedProvisionerServiceServer) ListWorkspaces(context.Context, *ListWorkspacesRequest) (*ListWorkspacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkspaces not implemented")
}
func (UnimplementedProvisionerServiceServer) ProvisionWorkspaceStream(*ProvisionWorkspaceRequest, grpc.ServerStreamingServer[ProvisionEvent]) error {
	return status.Errorf(codes.Unimplemented, "method ProvisionWorkspaceStream not implemented")
}
func (UnimplementedProvisionerServiceServer) DeleteWorkspace(context.Context, *Workspace) (*DeleteWorkspaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkspace not implemented")
}
func (UnimplementedProvisionerServiceServer) mustEmbedUnimplementedProvisionerServiceServer() {}
func (UnimplementedProvisionerServiceServer) testEmbeddedByValue()                            {}

// UnsafeProvisionerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProvisionerServiceServer will
// result in compilation errors.
type UnsafeProvisionerServiceServer interface {
	mustEmbedUnimplementedProvisionerServiceServer()
}

func RegisterProvisionerServiceServer(s grpc.ServiceRegistrar, srv ProvisionerServiceServer) {
	// If the following call pancis, it indicates UnimplementedProvisionerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProvisionerService_ServiceDesc, srv)
}

func _ProvisionerService_GetUserWorkspaceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserWorkspacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionerServiceServer).GetUserWorkspaceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvisionerService_GetUserWorkspaceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionerServiceServer).GetUserWorkspaceInfo(ctx, req.(*GetUserWorkspacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionerService_GetWorkspaceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Workspace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionerServiceServer).GetWorkspaceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvisionerService_GetWorkspaceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionerServiceServer).GetWorkspaceStatus(ctx, req.(*Workspace))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionerService_ListWorkspaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkspacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionerServiceServer).ListWorkspaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvisionerService_ListWorkspaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionerServiceServer).ListWorkspaces(ctx, req.(*ListWorkspacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProvisionerService_ProvisionWorkspaceStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProvisionWorkspaceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProvisionerServiceServer).ProvisionWorkspaceStream(m, &grpc.GenericServerStream[ProvisionWorkspaceRequest, ProvisionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProvisionerService_ProvisionWorkspaceStreamServer = grpc.ServerStreamingServer[ProvisionEvent]

func _ProvisionerService_DeleteWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Workspace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionerServiceServer).DeleteWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProvisionerService_DeleteWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionerServiceServer).DeleteWorkspace(ctx, req.(*Workspace))
	}
	return interceptor(ctx, in, info, handler)
}

// ProvisionerService_ServiceDesc is the grpc.ServiceDesc for ProvisionerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProvisionerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "provisioner.ProvisionerService",
	HandlerType: (*ProvisionerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserWorkspaceInfo",
			Handler:    _ProvisionerService_GetUserWorkspaceInfo_Handler,
		},
		{
			MethodName: "GetWorkspaceStatus",
			Handler:    _ProvisionerService_GetWorkspaceStatus_Handler,
		},
		{
			MethodName: "ListWorkspaces",
			Handler:    _ProvisionerService_ListWorkspaces_Handler,
		},
		{
			MethodName: "DeleteWorkspace",
			Handler:    _ProvisionerService_DeleteWorkspace_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProvisionWorkspaceStream",
			Handler:       _ProvisionerService_ProvisionWorkspaceStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/api/provisioner.proto",
}
