# Provisioner service configuration

# Namespace for the k8shell workspace
targetNamespace: ${TARGET_NAMESPACE}

clusterDomain: cluster.local

defaultRegistry:
  host: ${WORKSPACE_REGISTRY}
  # certCA: !file ${SECRET_FILES}/private_ca.pem
  username: !file ${SECRET_FILES}/registry_username
  password: !file ${SECRET_FILES}/registry_password

k8shellCapabilities:
  apiServerEnabled: true

certManager:
  enabled: false
  issuer:
    name: vault-root-issuer
    kind: ClusterIssuer
  duration: 24h
  renewBefore: 12h

# grpc server
grpc:
  port: 9030
  enableTLS: false
  certFile: /opt/shared/provisioner/tls/tls.crt
  keyFile: /opt/shared/provisioner/tls/tls.key

  # JWT required claims for authentication
  authEnabled: false
  audience: provisioner
  allowed:
    - serviceAccount: ssh-proxy
    - namespace: k8shell-test
      serviceAccount: ssh-proxy
    - namespace: k8shell-test
      serviceAccount: api-server
    
# NATS configuration for event streaming
nats:
  enabled: true
  url: nats://nats.k8shell-test:4222
  username: apiserver
  password: ${TOKEN_PROVISIONER}
  kv:
    # TTL for provision jobs in the NATS KV store
    provisionBucketTTL: 48h

# Identity service configuration
identity:
  address: identity.k8shell-test:9020
  tokenFilePath: /opt/shared/provisioner/identity-token
  caCertPath: /opt/shared/auth/ca.crt
  serverName: identity.k8shell-test.svc

# Identity JWT verifier configuration
# Used to validate user identity tokens
jwtVerifier:
  signingMethod: es256
  privateKeyFile: /opt/shared/auth/identity_private.pem

# Blueprints configuration
blueprints:
  directory: blueprints

