# Provisioner service configuration

# Namespace for the k8shell workspace
targetNamespace: k8shell-workspace

defaultRegistry:
  host: ${WORKSPACE_REGISTRY}
  certCA: !file ${SECRET_FILES}/private_ca.pem
  username: !file ${SECRET_FILES}/registry_username
  password: !file ${SECRET_FILES}/registry_password

# Server configuration
http:
  port: 9201
  APIKey: !file ${SECRET_FILES}/provisioner_key

# Identity service configuration
identity:
  baseURL: http://10.42.3.4:9090
  APIKey: !file ${SECRET_FILES}/identity_key
  timeout: 1000 

# Blueprints configuration
blueprints:
  directory: blueprints

