apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.__workspace__ }}-access-keys
  labels:
    {{- include "workspace.labels" . | nindent 4 }}  
    type: access-key
data:
  a1key: "{{ .Values.__a1key__ }}"
  a2key: "{{ .Values.__a2key__ }}"