{{- if .Values.__certmanager__.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
  namespace: {{ .Release.Namespace }} 
spec:
  secretName: {{ .Release.Name }}-tls
  duration: {{ .Values.__certmanager__.duration }}
  renewBefore: {{ .Values.__certmanager__.renewBefore }}
  commonName: {{ .Release.Name }}.{{ .Values.__targetnamespace__ }}.svc.cluster.local
  dnsNames:
    - {{ .Release.Name }}.{{ .Values.__targetnamespace__ }}
    - {{ .Release.Name }}.{{ .Values.__targetnamespace__ }}.svc
    - {{ .Release.Name }}.{{ .Values.__targetnamespace__ }}.svc.cluster.local
  usages:
    - server auth
  issuerRef:
    name: {{ .Values.__certmanager__.issuer.name }}
    kind: {{ .Values.__certmanager__.issuer.kind }}
{{- end }}