{{- $docker := .Values.docker | default dict -}}
{{- $k8shelld := .Values.k8shelld | default dict -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.__workspace__ }}-k8shelld-config
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "workspace.labels" . | nindent 4 }}  
    type: config-init
data:
  config.yaml: |-
    # system settings
    system:
      # true to enable profiling
      # if enabled, pprof will be available at localhost:6060
      pprof: false

      # api server 
      apiServer: 
        enabled: {{ .Values.__apiserver__.enabled }}
        address: http://api-server.{{ .Values.__namespace__ }}:9101

      # grpc server
      grpc:
        port: 2822

        {{- if .Values.__certmanager__.enabled }}
        enableTLS: true
        certFile: /etc/tls/k8shelld/tls.crt
        keyFile: /etc/tls/k8shelld/tls.key
        {{- else }}
        enableTLS: false
        {{- end }}

        audience: k8shelld
        allowed:
          {{- $conn := $k8shelld.connection -}}
          {{- $out := dict "ns" .Values.__namespace__ "sa" "ssh-proxy" -}}
          {{- if $conn }}
            {{- if $conn.allowAnyNS }}
              {{- $_ := set $out "ns" "*" }}
            {{- end }}
            {{- if $conn.allowAnySA }}
              {{- $_ := set $out "sa" "*" }}
            {{- end }}
          {{- end }}
          - namespace: {{ $out.ns | quote }}
            serviceAccount: {{ $out.sa | quote }}
          - namespace: {{ .Values.__namespace__ | quote }}
            serviceAccount: {{ "api-server" | quote }}

    {{- if .Values.splash }}
    # splash message shown to the user on workspace start
    splash: |
{{ .Values.splash | indent 6 }}
    {{- end }}

    {{- if .Values.portForwarding }}
    # port forwarding rules
    portForwarding:
    {{- range .Values.portForwarding }}
      - {{ . }}
    {{- end }}
    {{- end }}

    # reap zombie processes
    reapZombies:
      enabled: true

    # terminate orphaned processes, i.e. processes that were reparented to init (pid 1)
    terminateOrphans:
      enabled: true
      checkInterval: 5
      {{- if $k8shelld.ignoreOrphans }}
      exclude:
      {{- range $k8shelld.ignoreOrphans }}
      - {{ . }}
      {{- end }}
      {{- end }}
    
    # docker settings
    docker:
      enabled: {{ $docker.enabled | default false }}
      createDockerSockSymlink: {{ $docker.enabled | default false }}
      {{- $dockerStoragesYaml := include "workspace.storages" (dict "storages" $docker.storages) | trim }}
      {{- if eq $dockerStoragesYaml "[]" }}
      storages: []
      {{- else }}
      storages:
{{ $dockerStoragesYaml | nindent 8 }}
      {{- end }}

    {{- $storagesYaml := include "workspace.storages" (dict "storages" .Values.storages) | trim }}
    {{- if eq $storagesYaml "[]" }}
    storages: []
    {{- else }}
    storages:
{{ $storagesYaml | nindent 6 }}
    {{- end }}

    # apps
    # global switch to enable/disable apps
    enableApps: {{ .Values.enableApps | default false }}

    # apps configurations
    {{- if .Values.apps }}
    {{- $enabledApps := dict }}
    {{- range $name, $conf := .Values.apps }}
      {{- if $conf.enabled }}
        {{- $_ := set $enabledApps $name $conf }}
      {{- end }}
    {{- end }}
    {{- if gt (len $enabledApps) 0 }}
    apps:
    {{- range $name, $conf := $enabledApps }}
      {{ $name }}:
        listen: {{ $conf.listen }}
        binary: {{ $conf.binary | quote }}
        installAsRoot: {{ $conf.installAsRoot }}
        versionCmd:
        {{- range $arg := $conf.versionCmd }}
          - {{ $arg | quote }}
        {{- end }}
        versionRegex: {{ $conf.versionRegex | quote }}
        install: {{ $conf.install | quote }}
        start:
        {{- range $arg := $conf.start }}
          - {{ $arg | quote }}
        {{- end }}
        restartPolicy: {{ $conf.restartPolicy }}
        autoStart: {{ $conf.autoStart }}
        protocol: {{ $conf.protocol }}
    {{- end }}
    {{- end }}
    {{- end }}

    # identity token verification
    identity:
      tokenPath: {{ .Values.__jwtVerifier__.tokenPath }}
      publicKeyPath: {{ .Values.__jwtVerifier__.publicKeyPath }}
      signingMethod: {{ .Values.__jwtVerifier__.signingMethod }}
