apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.__workspace__ }}-k8shelld-config
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "workspace.labels" . | nindent 4 }}  
    type: config-init
data:
  config.yaml: |
    {{ .Values.__k8shelldconfig__ }} 