{{- if .Values.extFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.__workspace__ }}-main-ext-files
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "workspace.labels" . | nindent 4 }}  
    type: main-ext-files
data:
{{- range $path, $content := .Values.extFiles }}
  {{ $path | replace "/" "__" | quote }}: |
{{ $content | indent 4 }}
{{- end }}
{{- end }}
{{- if .Values.podman.extFiles }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.__workspace__ }}-podman-ext-files
  namespace: {{ .Release.Namespace }} 
  labels:
    {{ include "workspace.labels" . | nindent 4 }}  
    type: podman-ext-files
data:
{{- range $path, $content := .Values.podman.extFiles }}
  {{ $path | replace "/" "__" | quote }}: |
{{ $content | indent 4 }}
{{- end }}
{{- end }}
{{- if .Values.podman.containersConf }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.__workspace__ }}-podman-containers-conf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workspace.labels" . | nindent 4 }}
    type: podman-containers-conf
data:
  containers.conf: |
    [containers]
    netns="host"
    userns="host"
    ipcns="host"
    utsns="host"
    cgroupns="host"
    cgroups="disabled"
    log_driver = "k8s-file"
    [engine]
    cgroup_manager = "cgroupfs"
    events_logger="file"
    runtime="crun"
    [network]
    default_network = "host"
{{- end }}