apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-files
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "workspace.labels" . | nindent 4 }}  
    type: system
data:
  README: |
    # k8shell system files
    # This directory contains the system files for the k8shell workspace.
  {{- range $script := .Values.initScripts }}
  {{ $script.__file }}: |
{{ $script.script | indent 4 }}
  {{- end }}
