apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.__workspace__ }}
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "workspace.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    k8shell.io/type: workspace
    k8shell.io/workspace: {{ .Values.__workspace__ }}
  ports:
    - name: grpc-api
      port: 2822
      targetPort: 2822
      protocol: TCP
  type: ClusterIP
