{{- if eq .Values.network.networkPolicy "isolated" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-{{ .Values.__workspace__ }}-isolated
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "workspace.labels" . | nindent 4 }}  
spec:
  podSelector:
    matchLabels:
<<<<<<< HEAD
      app.kubernetes.io/name: k8shell-workspace
=======
      k8shell.io/app: k8shell-workspace
>>>>>>> 2af5c4e (ws policy fixes)
      k8shell.io/organization: {{ .Values.__organization__ }}
      k8shell.io/workspace: {{ .Values.__workspace__ }}
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
<<<<<<< HEAD
              kubernetes.io/metadata.name: {{ .Values.__namespace__ }}
            podSelector:
              matchLabels:
                k8shell.io/app: ssh-proxy
=======
              k8shell.io/app: k8shell-proxy 
>>>>>>> 2af5c4e (ws policy fixes)
  egress:
{{- if .Values.network.allowEgress }}
{{- range $cidr := .Values.network.allowEgress }}
    - to:
        - ipBlock:
            cidr: {{ $cidr }}
{{- end }}
{{- end }}
{{ include "default.egress" . | nindent 4 }}  
{{- end }}