{{- if eq .Values.network.networkPolicy "organization" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-{{ .Values.__workspace__ }}-organization
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "workspace.labels" . | nindent 4 }}  
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: k8shell-workspace
      k8shell.io/organization: {{ .Values.__organization__ }}
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: k8shell-workspace
              k8shell.io/organization: {{ .Values.__organization__ }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.__namespace__ }}
            podSelector:
              matchLabels:
                k8shell.io/app: ssh-proxy
  egress:
{{- if .Values.network.allowEgress }}
{{- range $cidr := .Values.network.allowEgress }}
    - to:
        - ipBlock:
            cidr: {{ $cidr }}
{{- end }}
{{- end }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: k8shell-workspace
              k8shell.io/organization: {{ .Values.__organization__ }}
              k8shell.io/blueprint: {{ .Values.__blueprint__ }}
{{ include "default.egress" . | nindent 4 }}  
{{- end }}