{{- if and .Values.network (eq .Values.network.networkPolicyClass "system") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-{{ .Release.Name }}-system
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "workspace.labels" . | nindent 4 }}  
spec:
  podSelector:
    matchLabels:
      k8shell.io/type: workspace
      k8shell.io/organization: "{{ .Values.__organization__ }}"
      k8shell.io/workspace: "{{ .Release.Name }}"
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - namespaceSelector: {}
        - ipBlock:
            cidr: 0.0.0.0/0
  egress:
    - to:
        - namespaceSelector: {}
        - ipBlock:
            cidr: 0.0.0.0/0
{{- if .Capabilities.APIVersions.Has "cilium.io/v2/CiliumNetworkPolicy" }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cilium-np-{{ .Release.Name }}-system
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workspace.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      k8shell.io/type: workspace
      k8shell.io/organization: {{ .Values.__organization__ }}
      k8shell.io/workspace: {{ .Release.Name }}
  egress:
    - toEntities:
        - world
        - cluster
{{- end }}
{{- end }}
