{{- if eq .Values.network.networkPolicy "user" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-{{ .Values.__workspace__ }}-user
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "workspace.labels" . | nindent 4 }}  
spec:
  podSelector:
    matchLabels:
      k8shell.io/app: k8shell-workspace
      k8shell.io/organization: {{ .Values.__organization__ }}
      k8shell.io/workspace: {{ .Values.__workspace__ }}
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              k8shell.io/app: k8shell-workspace
              k8shell.io/organization: {{ .Values.__organization__ }}
              k8shell.io/username: {{ .Values.__username__ }}
        - podSelector:
            matchLabels:
              k8shell.io/app: k8shell-workspace
              k8shell.io/organization: {{ .Values.__organization__ }}
              k8shell.io/networkPolicy: system
{{ include "default.ingress" . | nindent 4 }}  
  egress:
{{- if .Values.network.allowEgress }}
{{- range $cidr := .Values.network.allowEgress }}
    - to:
        - ipBlock:
            cidr: {{ $cidr }}
{{- end }}
{{- end }}
    - to:
        - podSelector:
            matchLabels:
              k8shell.io/app: k8shell-workspace
              k8shell.io/organization: {{ .Values.__organization__ }}
              k8shell.io/username: {{ .Values.__username__ }}
{{ include "default.egress" . | nindent 4 }}  
{{- end }}