{{- if eq .Values.network.networkPolicyClass "workspace" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-{{ .Values.__workspace__ }}-workspace
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "workspace.labels" . | nindent 4 }}  
spec:
  podSelector:
    matchLabels:
      k8shell.io/type: workspace
      k8shell.io/organization: {{ .Values.__organization__ }}
      k8shell.io/workspace: {{ .Values.__workspace__ }}
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              k8shell.io/type: workspace
              k8shell.io/organization: {{ .Values.__organization__ }}
              k8shell.io/blueprint: {{ .Values.__blueprint__ }}
        - podSelector:
            matchLabels:
              k8shell.io/type: workspace
              k8shell.io/organization: {{ .Values.__organization__ }}
              k8shell.io/network-policy: system
{{ include "default.ingress" . | nindent 4 }}  
  egress:
    - to:
        - podSelector:
            matchLabels:
              k8shell.io/type: workspace
              k8shell.io/organization: {{ .Values.__organization__ }}
              k8shell.io/blueprint: {{ .Values.__blueprint__ }}
{{ include "default.egress" . | nindent 4 }}  
{{- end }}