apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pat
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workspace.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.__pat__ | quote }}
