{{- $podman := .Values.podman | default dict -}}

{{- if .Values.storages }}
{{- range $storageName, $storage := .Values.storages }}
{{- if and $storage ($storage.enabled | default false) (ne ($storage.type | default "local") "memory") (ne ($storage.type | default "local") "emptyDir") (ne ($storage.type | default "local") "shared") }}
---
  {{- include "pvc-template" (dict "name" $storageName "storage" $storage "pvcPrefix" "" "ctx" $ ) }}
{{- end }}
{{- end }}
{{- end }}

{{- if ($podman.enabled | default false) }}
{{- if $podman.storages }}
{{- range $storageName, $storage := $podman.storages }}
{{- if and $storage ($storage.enabled | default false) }}
---
  {{- include "pvc-template" (dict "name" $storageName "storage" $storage "pvcPrefix" "podman-" "ctx" $ ) }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}