{{- $docker := .Values.docker | default dict -}}

{{- if .Values.storages }}
{{- range $storageName, $storage := .Values.storages }}
{{- if and $storage ($storage.enabled | default false) (not ($storage.memory | default false)) (ne ($storage.type | default "local") "shared") }}
---
  {{- include "pvc-template" (dict "name" $storageName "storage" $storage "pvcPrefix" "" "ctx" $ ) }}
{{- end }}
{{- end }}
{{- end }}

{{- if ($docker.enabled | default false) }}
{{- if $docker.storages }}
{{- range $storageName, $storage := $docker.storages }}
{{- if and $storage ($storage.enabled | default false) }}
---
  {{- include "pvc-template" (dict "name" $storageName "storage" $storage "pvcPrefix" "docker-" "ctx" $ ) }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}