apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.__workspace__ }}-tls
  namespace: {{ .Values.__namespace__ }}
type: Opaque
data:
  tls.crt: {{ .Values.__tlscrt__ | b64enc }}
  tls.key: {{ .Values.__tlskey__ | b64enc }}