{{- $podman := .Values.podman | default dict -}}
{{- $defaultSecurityContext := dict "runAsUser" 0 "runAsGroup" 0 -}}
{{- $securityContext := merge (dict) (.Values.securityContext | default dict) $defaultSecurityContext -}}
{{- $releaseName := .Release.Name }}

apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.splash }}
    workspace.k8shell.io/splash: {{ .Values.splash | b64enc | quote }}
    {{- end }}
    k8shell.io/manifest-hash: {{ .Values.__manifesthash__ | quote }}
    {{- if .Values.__identity__ }}
    k8shell.io/identity: {{ .Values.__identity__ | quote }}
    {{- end }}
    k8shell.io/userstr: {{ .Values.__userstr__ | quote }}
  labels:
    {{- include "workspace.workspaceLabels" . | nindent 4 }} 
spec:
  {{ if .Values.__registry__.regcred }}
  imagePullSecrets:
  - name: {{ .Values.__registry__.regcred }}
  {{ end }}  
  restartPolicy: OnFailure
  {{- if and .Values.subdomain .Values.hostname }}
  hostname: {{ .Values.hostname }}
  subdomain: {{ .Values.subdomain }}
  {{- end }}

  initContainers:
    #### init container to initialize the workspace
    - name: init-base
      image: {{ include "workspace.k8shelldImage" . }}
      imagePullPolicy: {{ .Values.k8shelld.imagePullPolicy }}
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      command:
        - /bin/sh
        - -c
        - |
          /k8shell/dist/scripts/init-base
          {{- include "workspace.storage.chownCommands" (dict "storages" .Values.storages "user" .Values.__user__) | nindent 10 }}
          {{- include "workspace.storage.chownCommands" (dict "storages" $podman.storages "user" .Values.__user__) | nindent 10 }}
      volumeMounts:
        - name: bin-volume
          mountPath: /usr/local/bin
        {{- include "workspace.storage.chownVolumeMounts" (dict "storages" .Values.storages "prefix" "" "user" .Values.__user__) | nindent 8 }}
        {{- include "workspace.storage.chownVolumeMounts" (dict "storages" $podman.storages "prefix" "podman-" "user" .Values.__user__) | nindent 8 }}

  containers:
    #### main container
    - name: k8shell-main
      image: {{ include "workspace.mainImage" . }}
      securityContext:
        {{- toYaml $securityContext | nindent 8 }}
      command: ["/usr/local/bin/k8shelld"] 
      imagePullPolicy: {{ .Values.imagePullPolicy }}
      resizePolicy:
      - resourceName: cpu
        restartPolicy: NotRequired
      - resourceName: memory
        restartPolicy: NotRequired      

      {{- if .Values.resources }}
      resources:
        requests:
          cpu: "0.1"
          memory: "128Mi"
        limits:
          {{- if .Values.resources.cpu }}
          cpu: {{ .Values.resources.cpu }}
          {{- end }}
          {{- if .Values.resources.memory }}
          memory: {{ .Values.resources.memory }}
          {{- end }}
      {{- end }}

      env:
      - name: IMAGE
        value:  {{ include "workspace.mainImage" . }}
      - name: WORKSPACE
        value: {{ .Release.Name }}
      - name: BLUEPRINT
        value: {{ .Values.__blueprint__ }}
      - name: USERNAME
        value: {{ .Values.__user__.username }}
      - name: USEREMAIL
        value: {{ .Values.__user__.email }}
      - name: USERFULLNAME
        value: {{ .Values.__user__.fullname }}
      {{- if .Values.__jwtverifierpublickey__ }}
      - name: JWT_VERIFIER_PUBLIC_KEY
        value: {{ .Values.__jwtverifierpublickey__ | b64enc | quote }}
      {{- end }}
      {{- if .Values.__jwtverifiersigningmethod__ }}
      - name: JWT_VERIFIER_SIGNING_METHOD
        value: {{ .Values.__jwtverifiersigningmethod__ | quote }}
      {{- end }}
      {{- if .Values.env }}    
      {{- range $envName, $envValue := .Values.env }}            
      - name: {{ $envName }}
        value: {{ $envValue }}
      {{- end }}
      {{- end }}
      
      volumeMounts:
      - name: bin-volume
        mountPath: /usr/local/bin/k8shelld
        subPath: k8shelld
        readOnly: true
      - name: bin-volume
        mountPath: /usr/local/bin/kbox
        subPath: kbox
        readOnly: true
      - name: bin-volume
        mountPath: /usr/local/bin/sftp
        subPath: sftp
        readOnly: true
      - name: config-volume
        mountPath: /etc/k8shell
        readOnly: true
      - name: main-volume
        mountPath: /usr/local/k8shell/system
        readOnly: true
      {{- if .Values.storages }}
      {{- range $storageName, $storage := .Values.storages }}
      {{- if and $storage (kindIs "map" $storage) ($storage.enabled | default false) }}
      - name: storage-{{ $storageName }}
        mountPath: {{ $storage.path }}
        readOnly: {{ $storage.readonly | default false }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.extFiles }}
      {{- range $path, $content := .Values.extFiles }}
      - name: main-ext-files-volume
        mountPath: {{ $path }}
        subPath: {{ $path | replace "/" "__" }}
      {{- end }}
      {{- end }}
      {{- if ($podman.enabled | default false) }}
      - name: podman-sock
        mountPath: /var/run/podman
        # readOnly: true
      {{- end }}
      {{- if .Values.__certmanager__.enabled }}
      - name: {{ .Release.Name }}-cert
        mountPath: /etc/tls/k8shelld
        readOnly: true
      {{- end }}


    #### podman engine container
    {{- if ($podman.enabled | default false) }}
    - name: k8shell-podman
      image: {{ $podman.image }}
      # command: ["/bin/sh"]
      # args:
      # - -c
      # - |
      #   trap '' TERM INT
      #   while true; do
      #     sleep 86400
      #   done

      command:
      - podman
      args:
      - system
      - service
      - --time=0
      - unix:///var/run/podman/podman.sock
        
      # see https://docs.k8shell.io/concepts/overview/security#least-privileged-workspace-containers
      {{- if $podman.securityContext }}
      securityContext:
        {{- toYaml $podman.securityContext | nindent 8 }}
      {{- end }}

      volumeMounts:
        - name: podman-sock
          mountPath: /var/run/podman
      {{- if .Values.__registry__.certCA }}
        - name: podman-ca-cert
          mountPath: /etc/ssl/certs/registry-ca.pem
          subPath: registry-ca.pem
      {{- end }}

      {{- if and ($podman.parentStorages | default false) .Values.storages }}    
      {{- range $storageName, $storage := .Values.storages }}
      {{- if and $storage (kindIs "map" $storage) ($storage.enabled | default false) }}
        - name: storage-{{ $storageName }}
          mountPath: {{ $storage.path }}
          readOnly: {{ $storage.readonly | default false }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if $podman.storages }}
      {{- range $storageName, $storage := $podman.storages }}
      {{- if and $storage (kindIs "map" $storage) ($storage.enabled | default false) }}
        - name: storage-podman-{{ $storageName }}
          mountPath: {{ $storage.path }}
          readOnly: {{ $storage.readonly | default false }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if $podman.extFiles }}
      {{- range $path, $content := $podman.extFiles }}
        - name: podman-ext-files-volume
          mountPath: {{ $path }}
          subPath: {{ $path | replace "/" "__" }}
      {{- end }}
      {{- end }}
    {{- end }}

  ####  list of volumes to mount into the containers
  volumes:
  - name: bin-volume
    emptyDir: {}
  - name: config-volume
    configMap:
      name: {{ .Release.Name }}-k8shelld-config
      items:
      - key: config.yaml
        path: config.yaml
      - key: blueprint.yaml
        path: blueprint.yaml
  - name: main-volume
    configMap:
      name: {{ .Release.Name }}-files
      defaultMode: 0755
      items:
      - key: README
        path: README
        {{- range $index, $script := .Values.initScripts }}
      - key: __init_{{ printf "%02d" (add $index 1) }}_{{ $script.name }}
        path: __init_{{ printf "%02d" (add $index 1) }}_{{ $script.name }}
        {{- end }}
  {{- if .Values.storages }}
  {{- range $storageName, $storage := .Values.storages }}
  {{- if and $storage (kindIs "map" $storage) ($storage.enabled | default false) }}
  - name: storage-{{ $storageName }}
    {{- if eq ($storage.type | default "local") "memory" }}
    emptyDir:
      medium: Memory
      {{- if $storage.sizeLimit }}
      sizeLimit: {{ $storage.sizeLimit }}
      {{- end }}
    {{- else if eq ($storage.type | default "local") "emptyDir" }}
    {{- if $storage.sizeLimit }}
    emptyDir:
      sizeLimit: {{ $storage.sizeLimit }}
    {{- else }}
    emptyDir: {}
    {{- end }}
    {{- else if eq ($storage.type | default "local") "shared" }}
    persistentVolumeClaim:
      claimName: pvc-{{ $storageName }}{{- if $storage.id }}-{{ $storage.id }}{{- end }}
    {{- else }}
    persistentVolumeClaim:
      claimName: pvc-{{ $releaseName }}-{{ $storageName }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if $podman.storages }}
  {{- range $storageName, $storage := $podman.storages }}
  {{- if and $storage (kindIs "map" $storage) ($storage.enabled | default false) }}
  - name: storage-podman-{{ $storageName }}
    persistentVolumeClaim:
      claimName: pvc-{{ $releaseName }}-podman-{{ $storageName }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.extFiles }}
  - name: main-ext-files-volume
    configMap:
      name: {{ $releaseName }}-main-ext-files
      items:
        {{- range $path, $content := .Values.extFiles }}
        - key: {{ $path | replace "/" "__" | quote }}
          path: {{ $path | replace "/" "__" }}
        {{- end }}
  {{- end }}
  {{- if ($podman.enabled | default false) }}
  - name: podman-sock
    emptyDir: {}
  {{- if $podman.extFiles }}
  - name: podman-ext-files-volume
    configMap:
      name: {{ $releaseName }}-podman-ext-files
      items:
        {{- range $path, $content := $podman.extFiles }}
        - key: {{ $path | replace "/" "__" | quote }}
          path: {{ $path | replace "/" "__" }}
        {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.__registry__.certCA }}
  - name: podman-ca-cert
    configMap:
      name: registryca
      items:
        - key: registry-ca.pem
          path: registry-ca.pem
  {{- end }}
  {{- if .Values.__certmanager__.enabled }}
  - name: {{ .Release.Name }}-cert
    secret:
      secretName: {{ .Release.Name }}-tls
  {{- end }}

  {{- if .Values.affinity }}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            {{- toYaml .Values.affinity | nindent 12 }}
  {{- end }}

  enableServiceLinks: false
