blueprints:
  - name: base
    isTemplate: true

    splash: |
      Welcome to k8shell - cloud-native workspaces on Kubernetes!
      Connected to k8shelld (version: {{.Version}}-{{.Commit}})
      For more information, visit https://k8shell.io

    image: docker.io/alpine:latest
    imagePullPolicy: IfNotPresent

    subdomain: !cel "user.organization"
    hostname: !cel "user.username + '-' + metadata.name"

    k8shelld:
      image: k8shell-base/k8shelld:pr-57-b9e9c39
      imagePullPolicy: IfNotPresent
      ignoreOrphans:
        - .*JetBrains.*

    network:
      networkPolicyClass: workspace

    resources:
      cpu: 4
      memory: 4Gi

    podman:
      enabled: false
      image: quay.io/podman/stable:v5.8.1

      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        appArmorProfile:
          type: Unconfined

      resources:
        cpu: 2
        memory: 2Gi

      # use the same volumes as in the main workspace
      parentStorages: true

      createDockerSockSymlink: true

    # list of storages in the workspace
    # storages:
    #   home:
    #     enabled: false
    #     storageClass: ""
    #     size: 10Gi
    #     path: !cel "'/home/' + user.username"
    #     readonly: False

    enableApps: false
    apps:
      vscode:
        enabled: false
        listen: 8080
        installAsRoot: true
        binary: "/usr/bin/code-server"
        versionCmd: ["/usr/bin/code-server", "--version"]
        versionRegex: "^([0-9]+\\.[0-9]+\\.[0-9]+)"
        install: |
          curl -fsSL https://code-server.dev/install.sh | sh
        start: ["/usr/bin/code-server", "--auth=none", "--bind-addr=127.0.0.1:8080", "."]
        restartPolicy: always
        protocol: "http"
