blueprints:
  - name: default
    shell: /bin/bash
    isTemplate: true
    sudo: false

    image: <image:tag>
    imagePullPolicy: Always

    subdomain: !cel "user.organization"
    hostname: !cel "user.username + '-' + metadata.name"

    k8shelld: 
      image: k8shell-base/k8shelld:v0.11.9-1
      imagePullPolicy: Always
      ignoreOrphans:
        - .*JetBrains.*
      # connection:
      #   allowAnyNS: false
      #   allowAnyNSA: false

    portForwarding:
      - localnetworks:0

    network:
      networkPolicy: workspace
      allowEgress:
        - 10.126.2.52/32

    resources:
      cpu: 2
      memory: 2Gi

    docker:
      enabled: false
      image: docker:28.0.4-dind

      resources:
        cpu: 2
        memory: 2Gi

      # group id used in the dind image to create the docker socket; when the dind image is rootless
      # the actual group id will be 100000 + group_id - 1 where 100000 is subordinate group id
      groupId: 999

      # subordinate group id used in the dind image; 
      # this should be set to 100000 when the dind image is rootless otehrwise it should be set to 0
      #subgid: 100000
      subgid: 0

      # use the same volumes as in the main workspace
      parentStorages: true

    # list of storages in the workspace
    storages:
      home:
        enabled: true
        storageClass: !cel env("WORKSPACE_STORAGE_CLASS")
        size: 10Gi
        path: !cel "'/home/' + user.username"
        readonly: False      
        annotations:
          zfs-csi.k8shell.io/volume-name: !cel "metadata.name + '/' + user.username"
          zfs-csi.k8shell.io/retain-on-delete: "true"
          zfs-csi.k8shell.io/squash: "all_squash"
          zfs-csi.k8shell.io/squash-uid: !cel "user.uid"
          zfs-csi.k8shell.io/squash-gid: !cel "user.gid"

      shared:
        enabled: true
        storageClass: !cel env("WORKSPACE_STORAGE_CLASS")
        size: 50Gi
        path: /opt/shared
        readonly: !cel "!(user.roles.exists(r, r in ['org-admin', 'admin', 'workspace-admin']))"
        annotations:
          zfs-csi.k8shell.io/volume-name: !cel "metadata.name + '/shared'"
          zfs-csi.k8shell.io/retain-on-delete: "true"

    initScripts:
      - workspace@: |
          ln -s /opt/shared $HOME/shared            

      - vscode@: |
          # add the vscode server settings
          mkdir -p $HOME/.vscode-server/data/Machine
          [ ! -f /$HOME/.vscode-server/data/Machine/settings.json ] && \
          if [ ! -f /$HOME/.vscode-server/data/Machine/settings.json ] && [ -f /opt/ext/vscode-server/settings.json ]; then
            cp /opt/ext/vscode-server/settings.json $HOME/.vscode-server/data/Machine/settings.json
          fi

      - git@: |
          # set the git configuration
          touch /$HOME/.gitconfig
          git config --global pull.rebase true
          git config --global user.name "${USERNAME}"
          git config --global user.email "${USEREMAIL}"

      - docker@: |
          [ -f $HOME/.docker/config.json ] && exit 0
          if [ -f /usr/local/bin/docker-credential-k8shell ]; then
            mkdir -p $HOME/.docker
            echo "{\"credsStore\":\"k8shell\"}" > $HOME/.docker/config.json
          fi
            

