blueprint:
  name: development
  template: default
  image: ${WORKSPACE_REGISTRY}/workspaces/dev:0.8-1.9

  credentialHelpers:
    docker:
      enabled: true

  docker:
    enabled: true

  serviceAccount: !cel |
    user.username in ['bruckins']
      ? "admin-sa"
      : "default"

  storages:
    home:
      annotations:
        zfs-csi.k8shell.io/volume-name: !cel "repo.owner + '/' + repo.name + '/' + user.username"
    shared:
      readonly: false
      annotations:
        zfs-csi.k8shell.io/volume-name: !cel "repo.owner2 + '/shared'"

  initScripts:
    - clone_repo@: |
        cd $HOME
        git config --global credential.helper k8shell
        git clone https://${GIT_ADDRESS}/${REPO_OWNER}/${REPO_NAME}.git