blueprint:
  name: identity
  template: development
  image: ${WORKSPACE_REGISTRY}/workspaces/dev:0.8-1.9
  shell: /bin/zsh
  sudo: true
  network_policy: system
  resources:
    cpu: 8
    memory: 8Gi

  initScripts:
    - init_repo@: |
        go env -w GOPRIVATE=github.com/k8shell-io/*
        cd $HOME/provisioner
        GOPATH="$HOME/go" go mod tidy