apiVersion: v2
name: workspace
description: k8shell workspace chart
version: 0.0.0 # set dynamically in the provisioner
appVersion: 0.0.0 # set dynamically in the provisioner

annotations:
  "app.kubernetes.io/managed-by": "k8shell"
